// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhjcomdoucmuwkkeppuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoamNvbWRvdWNtdXdra2VwcHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDkxNDksImV4cCI6MjA3MDU4NTE0OX0.DqXUrDBMiTxqGnuWy4ozn4g3mOiG13IelEXWMaJaWb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});